// src/app/core/components/AppAdRightAside.jsx
import React, { useEffect, useState } from 'react';
import { SentinelAdsService } from '../services/sentinel-ads.service.ts';
import { useAppStore } from '../../useAppStore.js';

export const AppAdRightAside = ({ position = 'RIGHT_ASIDE', onHasAdsChange }) => {
  const [announcements, setAnnouncements] = useState([]);
  const userSession = useAppStore(s => s.userSession);
  const userId = userSession?.id || userSession?.user_id || 'anonymous';
  const roleCode = userSession?.roles?.[0] || null;

  useEffect(() => {
    let isMounted = true;
    SentinelAdsService.getActiveAnnouncements(position, userId, roleCode)
      .then(ads => {
        if (isMounted) {
          const list = Array.isArray(ads) ? ads : [];
          setAnnouncements(list);
          if (onHasAdsChange) onHasAdsChange(list.length > 0);
        }
      })
      .catch(err => {
        console.warn('AppAdRightAside: error cargando anuncios:', err);
        if (onHasAdsChange) onHasAdsChange(false);
      });
    return () => { isMounted = false; };
  }, [position, userId, roleCode, onHasAdsChange]);

  const handleDismiss = async (announcementId) => {
    await SentinelAdsService.dismissAnnouncement(announcementId, userId);
    setAnnouncements(prev => {
      const updated = prev.filter(a => a.announcement_id !== announcementId);
      if (onHasAdsChange) onHasAdsChange(updated.length > 0);
      return updated;
    });
  };

  if (!announcements || announcements.length === 0) return null;

  return (
    <aside className="sentinel-ad-right-aside-container" style={{
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
      padding: '16px',
      width: '240px',
      minWidth: '200px',
      boxSizing: 'border-box',
      background: 'var(--bg-glass, rgba(10, 10, 12, 0.85))',
      borderLeft: '1px solid var(--border-color, #1e293b)',
      height: '100%',
      overflowY: 'auto',
      flexShrink: 0
    }}>
      <div style={{ borderBottom: '1px solid var(--border-color, #1e293b)', paddingBottom: '8px', textAlign: 'center' }}>
        <span style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-tertiary, #64748b)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Comunicados Sentinel
        </span>
      </div>
      {announcements.map(ad => (
        <div key={ad.announcement_id} className="sentinel-ad-card ad-right-aside" style={{
          background: 'rgba(15, 23, 42, 0.6)',
          border: '1px solid var(--border-light, rgba(6, 182, 212, 0.25))',
          borderRadius: '10px',
          padding: '14px',
          color: 'var(--text-primary, #f8fafc)'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
            <span style={{
              fontSize: '0.65rem',
              fontWeight: 700,
              padding: '2px 6px',
              borderRadius: '4px',
              textTransform: 'uppercase',
              background: ad.announcement_type === 'CRITICAL' ? '#ef4444' : ad.announcement_type === 'WARNING' ? '#f59e0b' : 'var(--accent-primary, #06b6d4)',
              color: '#fff'
            }}>
              {ad.announcement_type || 'INFO'}
            </span>
            {ad.is_dismissible && (
              <button 
                onClick={() => handleDismiss(ad.announcement_id)}
                title="Cerrar"
                style={{ background: 'none', border: 'none', color: 'var(--text-tertiary, #64748b)', fontSize: '1.1rem', cursor: 'pointer' }}
              >
                &times;
              </button>
            )}
          </div>
          <h4 style={{ margin: '0 0 6px 0', fontSize: '0.92rem', fontWeight: 600, color: 'var(--text-primary)' }}>{ad.title}</h4>
          <p style={{ margin: '0 0 10px 0', fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>{ad.message}</p>
          {ad.action_url && (
            <a 
              href={ad.action_url} 
              target="_blank" 
              rel="noopener noreferrer"
              style={{
                display: 'block',
                width: '100%',
                textAlign: 'center',
                padding: '6px 12px',
                fontSize: '0.78rem',
                fontWeight: 600,
                color: '#fff',
                background: 'linear-gradient(135deg, var(--accent-primary), var(--accent-secondary))',
                borderRadius: '6px',
                textDecoration: 'none',
                boxSizing: 'border-box'
              }}
            >
              {ad.action_label || 'Más información'}
            </a>
          )}
        </div>
      ))}
    </aside>
  );
};

// src/app/core/components/app-ad-right-aside.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SentinelAdsService, IAnnouncement } from '../services/sentinel-ads.service';

@Component({
  selector: 'app-ad-right-aside',
  standalone: true,
  imports: [CommonModule],
  template: `
    <aside *ngIf="announcements.length > 0" class="sentinel-ad-right-aside-container">
      <div class="aside-header">
        <span class="aside-label">Comunicados Sentinel</span>
      </div>
      <div *ngFor="let ad of announcements" class="sentinel-ad-card ad-right-aside">
        <div class="ad-header">
          <span class="ad-badge" [ngClass]="ad.announcement_type?.toLowerCase()">
            {{ ad.announcement_type || 'INFO' }}
          </span>
          <button 
            *ngIf="ad.is_dismissible" 
            class="ad-dismiss-btn" 
            (click)="dismiss(ad.announcement_id)" 
            title="Cerrar"
          >
            &times;
          </button>
        </div>
        <h4 class="ad-title">{{ ad.title }}</h4>
        <p class="ad-message">{{ ad.message }}</p>
        <a 
          *ngIf="ad.action_url" 
          [href]="ad.action_url" 
          target="_blank" 
          rel="noopener noreferrer" 
          class="ad-action-btn"
        >
          {{ ad.action_label || 'Más información' }}
        </a>
      </div>
    </aside>
  `,
  styles: [`
    .sentinel-ad-right-aside-container {
      display: flex;
      flex-direction: column;
      gap: 16px;
      padding: 16px;
      width: 240px;
      min-width: 200px;
      box-sizing: border-box;
      background: var(--bg-glass, rgba(10, 10, 12, 0.85));
      border-left: 1px solid var(--border-color, #1e293b);
      height: 100%;
      overflow-y: auto;
    }
    .aside-header {
      border-bottom: 1px solid var(--border-color, #1e293b);
      padding-bottom: 8px;
      text-align: center;
    }
    .aside-label {
      font-size: 0.7rem;
      font-weight: 700;
      color: var(--text-tertiary, #64748b);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .sentinel-ad-card {
      background: rgba(15, 23, 42, 0.6);
      border: 1px solid var(--border-light, rgba(6, 182, 212, 0.2));
      border-radius: 10px;
      padding: 14px;
      color: var(--text-primary, #f8fafc);
    }
    .ad-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }
    .ad-badge {
      font-size: 0.65rem;
      font-weight: 700;
      padding: 2px 6px;
      border-radius: 4px;
      text-transform: uppercase;
      background: var(--accent-primary, #06b6d4);
      color: #fff;
    }
    .ad-badge.warning { background: #f59e0b; }
    .ad-badge.critical { background: #ef4444; }
    .ad-badge.feature { background: #8b5cf6; }
    .ad-dismiss-btn {
      background: transparent;
      border: none;
      color: var(--text-tertiary, #64748b);
      font-size: 1.1rem;
      cursor: pointer;
    }
    .ad-dismiss-btn:hover { color: #ef4444; }
    .ad-title { margin: 0 0 6px 0; font-size: 0.92rem; font-weight: 600; }
    .ad-message { margin: 0 0 10px 0; font-size: 0.82rem; color: var(--text-secondary); line-height: 1.4; }
    .ad-action-btn {
      display: block;
      width: 100%;
      text-align: center;
      padding: 6px 12px;
      font-size: 0.78rem;
      font-weight: 600;
      color: #fff;
      background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary));
      border-radius: 6px;
      text-decoration: none;
      box-sizing: border-box;
    }
  `]
})
export class AppAdRightAsideComponent implements OnInit {
  @Input() userId: string = 'anonymous';
  public announcements: IAnnouncement[] = [];

  async ngOnInit() {
    await this.loadAnnouncements();
  }

  async loadAnnouncements() {
    this.announcements = await SentinelAdsService.getActiveAnnouncements('RIGHT_ASIDE', this.userId);
  }

  async dismiss(announcementId: string) {
    await SentinelAdsService.dismissAnnouncement(announcementId, this.userId);
    this.announcements = this.announcements.filter(a => a.announcement_id !== announcementId);
  }
}
